/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#b4b3b3",
        "on-tertiary-fixed-variant": "#474747",
        "background": "#fff8f4",
        "outline": "#867466",
        "on-background": "#1d1b19",
        "on-secondary-fixed": "#360c19",
        "surface-dim": "#dfd9d5",
        "surface-tint": "#8e4e00",
        "primary-fixed": "#ffdcc1",
        "surface-container-highest": "#e8e1dd",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#2e1500",
        "secondary-container": "#feb6c4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f2ee",
        "surface-container": "#f3ede9",
        "secondary": "#864e5a",
        "primary": "#8e4e00",
        "inverse-surface": "#33302d",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-tertiary": "#ffffff",
        "on-surface": "#1d1b19",
        "secondary-fixed": "#ffd9df",
        "primary-container": "#f6a04d",
        "outline-variant": "#d9c2b2",
        "on-error-container": "#93000a",
        "surface-container-high": "#eee7e3",
        "on-tertiary-container": "#454545",
        "primary-fixed-dim": "#ffb878",
        "on-error": "#ffffff",
        "surface-variant": "#e8e1dd",
        "on-secondary": "#ffffff",
        "tertiary": "#5e5e5e",
        "surface-bright": "#fff8f4",
        "inverse-primary": "#ffb878",
        "on-primary-fixed-variant": "#6c3a00",
        "on-tertiary-fixed": "#1b1c1c",
        "error": "#ba1a1a",
        "on-primary-container": "#6a3900",
        "secondary-fixed-dim": "#fbb3c1",
        "inverse-on-surface": "#f6efeb",
        "tertiary-fixed": "#e4e2e2",
        "surface": "#fff8f4",
        "on-surface-variant": "#534437",
        "on-secondary-fixed-variant": "#6b3743",
        "on-secondary-container": "#7a4450",
        "on-primary": "#ffffff"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
